language: python

python:
  - "2.7"
  - "3.3"
  - "pypy"

matrix:
  allow_failures:
    # mysterious RPython KeyError's
    - python: pypy

services:
  - riak
  - redis-server

install:
  - sudo apt-get update -qq
  - sudo apt-get install protobuf-compiler
  - pip install -r requirements.travis.txt
  - pip install coveralls

before_script:
  # replace with the correct version of .coveragerc, when run under Python 3
  - "[ \"x${TRAVIS_PYTHON_VERSION%.?}\" == \"x3\" ] && ( echo Switching .coveragerc to Python 3 version. ; rm .coveragerc && ln -s .coveragerc.py3 .coveragerc ) ; true"
  - ls -l .coveragerc


script: nosetests --with-coverage

after_success:
  - coveralls

notifications:
  email: false


# vim:set ai et ts=2 sw=2 sts=2 fenc=utf-8:
