language: python

python:
  - "2.7"
  - "pypy"

services:
  - riak
  - redis-server

install:
  # Directly using [[ xxx ]] && xxx would make the command as a whole *fail*
  # if xxx is not true, *aborting* the Travis build. So we have to use an if
  # stmt to wrap the conditional things ("|| true" is not as elegant).
  - "if [[ ${TRAVIS_PYTHON_VERSION} == 'pypy' ]]; then sudo add-apt-repository -y ppa:pypy/ppa ; fi"
  - sudo apt-get update -qq
  - sudo apt-get install protobuf-compiler

  # Use official PyPy package
  # This is inspired by what the pip project has done.
  - "if [[ ${TRAVIS_PYTHON_VERSION} == 'pypy' ]]; then sudo apt-get install -y pypy ; fi"
  - "if [[ ${TRAVIS_PYTHON_VERSION} == 'pypy' ]]; then sudo rm -rf /usr/local/pypy/bin ; fi"
  - "if [[ ${TRAVIS_PYTHON_VERSION} == 'pypy' ]]; then python --version ; fi"

  # Prepare Python environment
  - pip install -U setuptools pip --use-mirrors
  - pip install -r requirements.txt --use-mirrors

before_script:
  - search-cmd install users
  - search-cmd set-schema users ${TRAVIS_BUILD_DIR}/install/rs-schema/users.config

script: nosetests

notifications:
  email: false


# vim:set ai et ts=2 sw=2 sts=2 fenc=utf-8:
