language: python

python:
  - "2.7"
  # - "3.3"
  - "pypy"

matrix:
  allow_failures:
    # - python: 3.3
    - python: pypy

services:
  - riak
  - redis-server

before_install:
  - 'if [[ "x${TRAVIS_PYTHON_VERSION%.?}" == "x3" ]]; then export IS_PY3K=true ; else export IS_PY3K=false ; fi'
  - 'if [[ "${TRAVIS_PYTHON_VERSION}" == "pypy" ]]; then export IS_PYPY=true ; else export IS_PYPY=false ; fi'

  # apt index
  - '${IS_PY3K} || sudo apt-get update -qq'

  # Python deps
  - 'if ${IS_PY3K}; then export REQ_FILE=requirements.py3.txt ; else export REQ_FILE=requirements.txt ; fi ; printf "\033[1;32m * \033[mUsing requirements file: ${REQ_FILE}\n"'


install:
  # Protobuf deps, only applicable if not running Python 3.x
  - '${IS_PY3K} || sudo apt-get install protobuf-compiler'

  # gevent, needs master if on PyPy
  - '${IS_PYPY} && git clone https://github.com/surfly/gevent.git && ( cd gevent && ./setup.py develop )'

  # Python deps
  - pip install -r "${REQ_FILE}"
  # riak depends on riak-pb which pulls in protobuf, which is not supported by
  # Python 3.x at the moment. So we have to exclude it from weiyu's deps, and
  # install it ourselves, ignoring deps.
  - 'if ${IS_PY3K}; then pip install riak --no-deps ; fi'

  # coveralls.io integration
  - pip install coveralls

before_script:
  # replace with the correct version of .coveragerc, when run under Python 3
  - 'if ${IS_PY3K}; then echo Switching .coveragerc to Python 3 version. ; rm .coveragerc && ln -s .coveragerc.py3 .coveragerc ; fi'
  - ls -l .coveragerc
  # specify the proper Rainfile to use
  - 'if ${IS_PY3K}; then export RAINFILE_TO_USE=Rain.d/travis/config.py3.yml ; else export RAINFILE_TO_USE=Rain.d/travis/config.yml ; fi ; printf "\033[1;32m * \033[mUsing Rainfile: ${RAINFILE_TO_USE}\n"'


script: nosetests --with-coverage

after_success:
  - coveralls

notifications:
  email: false


# vim:set ai et ts=2 sw=2 sts=2 fenc=utf-8:
