language: python

python:
  - "2.7"
  - "pypy"

services:
  - riak
  - redis-server

install:
  - sudo apt-get update -qq
  - sudo apt-get install protobuf-compiler

  # Use official PyPy package
  # This is inspired by what the pip project has done.
  - "[[ ${TRAVIS_PYTHON_VERSION} == 'pypy' ]] && sudo add-apt-repository -y ppa:pypy/ppa"
  - "[[ ${TRAVIS_PYTHON_VERSION} == 'pypy' ]] && sudo apt-get install -y pypy"
  - "[[ ${TRAVIS_PYTHON_VERSION} == 'pypy' ]] && sudo rm -rf /usr/local/pypy/bin"

  # Prepare Python environment
  - pip install -U setuptools pip --use-mirrors
  - pip install -r requirements.txt --use-mirrors

before_script:
  - search-cmd install users
  - search-cmd set-schema users ${TRAVIS_BUILD_DIR}/install/rs-schema/users.config

script: nosetests

notifications:
  email: false


# vim:set ai et ts=2 sw=2 sts=2 fenc=utf-8:
