$$include:
  - Rain.d/site.yml


# 数据库配置
weiyu.db:
  databases:
    $$include: Rain.d/db.databases.for-travis.py3.yml

  storage:
    $$include: Rain.d/db.storage.yml


# vim:set ai et ts=2 sw=2 sts=2 fenc=utf=8:
