site:
  $$nodup: true

  session:
    backend: redis
    options:
      struct_id: luohua.session
      cookie-key: lh_s
      secret: '7h1z_must_13e_s3cr37'
      ttl: 3600

  staticfile:
    root: ../jnrain2/static/

  middlewares:
    pre:
      - session
      - luohua.metrics
      - luohua.session.user
    post:
      - luohua.metrics
      - session

  views:
    package: luohua.app
    modules:
      # API 界面
      - .v1.session
      - .v1.account
      - .v1.vpool
      - .v1.vtag
      - .v1.vthread
      - .v1.vfile
      - .v1.univ

      # 杂项 API
      - .misc

      # 中间件
      - .metrics.middleware
      - .session.middleware

      # 实时信道
      - .rt
      - luohua.rt.ns


# vim:set ai et ts=2 sw=2 sts=2 fenc=utf=8:
